// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZsSjN3FgPdGbfgxI1oZKmpWFdiV8c88',
    appId: '1:105711281116:web:f35e5a6f4e8750f871a519',
    messagingSenderId: '105711281116',
    projectId: 'lejaao',
    authDomain: 'lejaao.firebaseapp.com',
    storageBucket: 'lejaao.firebasestorage.app',
    measurementId: 'G-27C2CGKK48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDge2Uq-PRI2HvBvx3jC817fo5pti2_x7g',
    appId: '1:105711281116:android:e800a1526b2b156771a519',
    messagingSenderId: '105711281116',
    projectId: 'lejaao',
    storageBucket: 'lejaao.firebasestorage.app',
  );
} 